<div class="page-container">
   <div class="grid-container">
     <div class="grid">
       <div ng-controller="LoginController" class="signin-register-wrap cell ng-scope">
         <div class="signin-container">
             <div>
               <h1 class="signin-head ng-scope">Sign In</h1>
               <div class="login-form-wrap ng-scope">
                  <div class="error"><?= $this->error ? '<p class="error">'.$this->error.'</p>' : "" ?></div>
                 <form name="loginForm" class="ng-pristine ng-valid" action="/dang-nhap.html" method="POST">
                  <input name="type" type="hidden" value="email">
                  <input name="<?= $this->form->getElements()['csrf']->getName()?>" type="hidden" value="<?= $this->form->getElements()['csrf']->getValue()?>">
                  <div class="form-fields-wrapper">
                   <label class="no-acc-txt mar-btm-10">EMAIL ADDRESS</label>
                   <input type="text" class="gs-textbox ng-pristine ng-untouched ng-valid required" id="username" placeholder="email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'email'" name="<?=$this->form->getElements()['user_name']->getName()?>">
                </div>
                <div class="form-fields-wrapper">
                   <label class="no-acc-txt mar-btm-10">PASSWORD</label>
                   <input type="password" class="gs-textbox ng-pristine ng-untouched ng-valid required" id="password" placeholder="password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'password'" name="<?= $this->form->getElements()['user_password']->getName()?>">
                   </div>
                   <div class="form-fields-wrapper">
                   <button type="submit" class="gs-button mar-top-5">Sign In</button>
                </div>
                   <div style="clear: both;"></div>
                 </form>
               </div>
             </div>
             <div class="not-registered-wrap center ng-scope">
               <h1 class="no-acc-txt pad-top-25 pad-btm-25">DON’T HAVE AN ACCOUNT? <a href="/dang-ky.html"><span> REGISTER</span><div class="align-middle"></div></a></h1>
             </div>
               <?php echo $this->partial('partials/login-social.phtml')?>
         </div>
       </div>
     </div>
   </div>
</div>