<div class="page-container">
   <div class="grid-container">
     <div class="grid">
       <div ng-controller="LoginController" class="signin-register-wrap cell ng-scope">
         <div class="signin-container">
             <div>
               <h1 class="signin-head ng-scope">Đăng ký </h1>
               <div class="login-form-wrap ng-scope">
                  <div class="error"><?= $this->error ? '<p class="error">'.$this->error.'</p>' : "" ?></div>
               <form accept-charset="UTF-8" action="/dang-ky.html" class="ng-pristine ng-valid" data-event-name="regular email log in attempt" id="form-register" method="post">
                  <input name="<?= $this->form->getElements()['csrf']->getName()?>" type="hidden" value="<?= $this->form->getElements()['csrf']->getValue()?>">
                  <div class="form-fields-wrapper">
                     <label class="no-acc-txt mar-btm-10">EMAIL ADDRESS</label>
                     <input type="text" class="gs-textbox ng-pristine ng-untouched ng-valid required" id="username" placeholder="email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'email'" name="<?=$this->form->getElements()['user_name']->getName()?>" value="<?=$this->form->getElements()['user_name']->getValue()?>">
                  </div>
                  <div class="form-fields-wrapper">
                     <label class="no-acc-txt mar-btm-10">PASSWORD</label>
                     <input type="password" class="gs-textbox ng-pristine ng-untouched ng-valid required" id="password" placeholder="password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'password'" name="<?= $this->form->getElements()['user_password']->getName()?>">
                  </div>
                  <div class="form-fields-wrapper">
                     <label class="no-acc-txt mar-btm-10">PASSWORD</label>
                     <input type="password" class="gs-textbox ng-pristine ng-untouched ng-valid required" id="confirm-password" placeholder="password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'password'" name="<?= $this->form->getElements()['confirm_password']->getName()?>">
                  </div>
                  <div class="form-fields-wrapper">
                     <label class="no-acc-txt mar-btm-10">Display name</label>
                     <input type="text" class="gs-textbox ng-pristine ng-untouched ng-valid required" id="username" placeholder="Display name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Display name'" name="<?=$this->form->getElements()['user_display_name']->getName()?>" value="<?=$this->form->getElements()['user_display_name']->getValue()?>">
                  </div>
                  <div class="form-fields-wrapper">
                     <label class="no-acc-txt mar-btm-10">Phone</label>
                     <input type="text" class="gs-textbox ng-pristine ng-untouched ng-valid required" id="username" placeholder="Phone" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Phone'" name="<?=$this->form->getElements()['user_phone']->getName()?>" value="<?=$this->form->getElements()['user_phone']->getValue()?>">
                  </div>
                  
                  <div class="not-registered-wrap center ng-scope">
                     <h1 class="no-acc-txt pad-top-25 pad-btm-25">ALREADY HAVE AN ACCOUNT ? <a href="/dang-nhap.html"><span> Đăng nhập </span><div class="align-middle"></div></a></h1>
                  </div>
                  <div class="form-fields-wrapper">
                     <button type="submit" class="gs-button mar-top-5">Đăng ký </button>
                  </div>
                  <div style="clear: both;"></div>
                  <div class="form-fields-wrapper">
                     <div class="form-steps-bottom"></div>
                  </div>
                  <?php echo $this->partial('partials/login-social.phtml')?>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
</div>
