<footer class="site-footer">
  <div class="grid-container">
    <div class="grid">
      <div class="app-promo cell">
        <div class="gs-app-image">
          <img src="<?php echo $this->baseUrl("static/images/icon-app.png");?>" alt="GLAMSQUAD app">
        </div>
        <form name="appPromoForm" class="gs-form ng-pristine ng-valid">
          <h5 class="comp-subhead">tải ngay ứng dụng</h5>
          <h4>quản lý dịch vụ và lịch hẹn tốt hơn.</h4>
          <sms-app-link></sms-app-link>
          <a href="javascript:void(0)" class="app-store-link" target="_blank">
            <img src="<?php echo $this->baseUrl("static/images/icon-download-ios.png");?>" alt="Download on the App Store">
          </a>
          <a href="javascript:void(0)" class="app-store-link" target="_blank">
            <img src="<?php echo $this->baseUrl("static/images/icon-download-android.png");?>" alt="Download on the CHPlay">
          </a>
        </form>
      </div>
      <div class="links cell">
        <section class="site-links">
          <?php $helper = new Helpers_View_Menu();?>
          <?= $helper->bottomMenu() ?>
          <div class="mobile-app">
            <h6>Mobile App</h6>
            <a href="https://itunes.apple.com/us/app/glamsquad/id766676007?mt=8&amp;uo=4" class="app-store-link">
              <img src="https://www.glamsquad.com/wp-content/themes/phoenix/app/images/dist/global/download-app.svg" alt="Download on the App Store">
            </a>
          </div>
        </section>
        <ul class="social-links">
          <li>
            <a href="https://www.instagram.com/vapor.vn/" target="_blank">
              <img src="<?php echo $this->baseUrl("static/images/icon-instagram.png");?>" />
            </a>
          </li>
          <li>
            <a href="https://www.facebook.com/Vapor.book/" target="_blank">
              <img src="<?php echo $this->baseUrl("static/images/icon-fb.png");?>" />
            </a>
          </li>
          <li>
            <a href="https://twitter.com/Vaporvn" target="_blank">
              <img src="<?php echo $this->baseUrl("static/images/icon-twitter.png");?>" />
            </a>
          </li>
          <li>
            <a href="javascript:void(0)" target="_blank">
              <img src="<?php echo $this->baseUrl("static/images/icon-pinterest.png");?>" />
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>