<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="<?php echo $this->baseUrl("/static/js/jquery.min.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/jquery-ui.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/bootstrap.min.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/easing.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/jquery.flexslider-min.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/jquery.steps.min.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/jquery.validate.min.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/moment.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/bootstrap.min.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/bootstrap-datetimepicker.min.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/bootstrap-dropdownhover.min.js")?>"></script>
<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyBVeWQlpgrEUI1h5fUDYJLj9JlbU6UGmHE&region=VN">
    </script>
<script src="<?php echo $this->baseUrl("/static/js/jquery.placepicker.min.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/js.cookie.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/jquery.loading.min.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/all.js?v=5")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/booking.js?v=4")?>"></script>
