<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="<?php echo $this->baseUrl("/static/js/jquery.min.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/jquery-ui.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/bootstrap.min.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/easing.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/jquery.flexslider-min.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/jquery.steps.min.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/jquery.validate.min.js")?>"></script>
<script src="<?php echo $this->baseUrl("/static/js/custom.js")?>"></script>

<script src="<?php echo $this->baseUrl("/static/js/dpNumberPicker-2.x-min.js")?>"></script>