<!-- SEO Ultimate -->
  <meta property="og:type" content="article">
  <meta property="og:title" content="Vapor | An on-demand, in-home service in HC">
  <meta property="og:url" content="https://www.vapor.vn/">
  <meta property="article:published_time" content="2017-10-01">
  <meta property="article:modified_time" content="2017-10-02">
  <meta property="og:site_name" content="VAPOR">
  <meta name="twitter:card" content="summary">

  <title>Đặt dịch vụ máy lạnh chỉ trong 60 giây </title>

  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/favicon.ico" type="image/x-icon">
  
<!-- /SEO Ultimate -->