<header class="site-header" ng-class="{'nav-open': siteNav}">
  <div class="header-container">
    <a href="/" class="logo-link">
      <img src="<?php echo $this->baseUrl("static/images/logo-vapor.png");?>" alt="VAPOR" class="gs-logo-wordmark">
    </a>
    <nav class="site-nav">
      <ul>
        <?php $helper = new Helpers_View_Menu();?>
        <?= $helper->topMenu() ?>
        <?php $user = $this->authen();
              if($user) { ?>
              <li class="sign-in" style="margin-left: auto;">
                <a href="/user/<?=$user->getId()?>">welcome, <?= $user->getUserDisplayName()?></a>
              </li>
              <?php } else {?>
              <li class="sign-in" style="margin-left: auto;">
                <a href="/dang-nhap.html">đăng nhập</a>
              </li>
              <?php }?>
              <li id="thamgia" class="book-now" style="margin-left: inherit!important;">
                <label class="switch">
                  <input type="checkbox">
                  <span class="slider round"></span>
                </label>
              </li>
      </ul>
    </nav>
  </div>
</header>