<header class="site-header" ng-class="{'nav-open': siteNav}">
  <div class="header-container">
    <a href="/" class="logo-link">
      <img src="<?php echo $this->baseUrl("static/images/logo-vapor.png");?>" alt="VAPOR" class="gs-logo-wordmark">
    </a>
    <nav class="site-nav">
      <ul>
        <?php $helper = new Helpers_View_Menu();?>
        <?= $helper->topMenu() ?>

        <li class="sign-in" id="topmenu-user-info" style="margin-left: auto;">
          <?php echo $this->action('topmenu', 'user')?>
        </li>

        <li id="thamgia" class="thamgia" style="margin-left: inherit!important;">
          <label class="switch">
            <input type="checkbox" class="slide-btn">
            <span class="slider round"></span>
          </label>
        </li>
      </ul>
    </nav>
  </div>
</header>