<link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/booking.css")?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/w3.css")?>">
<link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/bootstrap-datetimepicker.min.css")?>">

<div class="page-container">
   <bf-booking-flow class="bf-booking-flow">
      <div class="booking-flow steps">
        <h3>step 1</h3>
         <section class="booking-flow-section booking-flow-services" style="">
            <div class="grid-container-full">
               <div class="col-4-8 grid">
                  <div class="booking-flow-steps cell">
                     <a href="/" class="logo-link">
                     <h2>VAPOR</h2>
                     </a>
                     <div class="step-details ng-binding">Bước 1 - 4</div>
                     <h1 class="booking-flow-title">Vui lòng chọn dịch vụ mà bạn muốn đặt.</h1>
                  </div>
                  <div class="booking-flow-content cell" id="booking-list-machine">
                     <nav class="service-type-nav">
                        <ul>
                          <?php foreach ($this->services as $id => $service) {?>
                            <li class="ng-binding ng-scope active">
                              <a data-toggle="tab" href="#<?=$service->getServiceSlug()?>"><?=$service->getServiceTitle()?></a>
                           </li>
                          <?php }?>
                        </ul>
                     </nav>
                     <?php foreach ($this->services as $key => $service) {?>
                     <ul class="booking-services services" id="<?=$service->getServiceSlug()?>">
                        <?php $listMachine = $service->getListMachine()?>
                        <?php foreach ($listMachine as $machine) {?>
                        <li class="service ng-scope" data-title="<?=$machine->getMachineTitle()?>" data-service="<?=$service->getServiceTitle()?>">
                          <div class="booking-cell">
                            <div class="left-cell">
                              <div class="header"><p><?=$machine->getMachineTitle()?></p></div>
                              <img alt="BLOWOUT" class="service-image" src="<?=$machine->getMachineImage()?>">
                            </div>
                            <div class="right-cell">
                              <div class="header">
                                <div class="column">Công suất </div>
                                <div class="column">Số lượng </div>
                              </div>
                          <?php $listPower = $machine->getListPower()?>
                          <?php foreach ($listPower as $detailService) {?>
                            <div class="row" data-service-title="<?=$service->getServiceTitle()?>" data-machine-title="<?=$machine->getMachineTitle()?>" data-service-id="<?=$detailService->getId()?>" data-power="<?=$detailService->getServicesPower()?>" data-service-count="">
                                <div class="column"><?=$detailService->getServicesPower()?></div>
                                <div class="column">
                                  <div class="input-group number-spinner">
                                    <span class="input-group-btn">
                                      <button  type="button" class="btn btn-default" data-dir="dwn">
                                        <span class="glyphicon glyphicon-minus">
                                          <i class="fa fa-minus" aria-hidden="true"></i>
                                        </span>
                                      </button>
                                    </span>
                                    <input data-service-title="<?=$service->getServiceTitle()?>" data-machine-title="<?=$machine->getMachineTitle()?>" data-service-id="<?=$detailService->getId()?>" data-power="<?=$detailService->getServicesPower()?>" data-service-count="" type="text" class="form-control text-center service-detail" data-service-cost="<?=$detailService->getServicesCost()?>" id="" value="0">
                                    <span class="input-group-btn">
                                      <button type="button"  class="btn btn-default" data-dir="up">
                                        <span class="glyphicon glyphicon-plus">
                                          <i class="fa fa-plus" aria-hidden="true"></i>
                                        </span>
                                      </button>
                                    </span>
                                  </div>
                                </div>
                              </div>
                          <?php }?>
                            </div>
                          </div>
                        </li>
                        <?php }?>
                               
                     </ul>
                     <?php }?>
                     <bf-services-summary>
                        <section class="booking-panel">
                          <div class="summary">
                          </div>
                          <div style="text-align: right">
                            <span class="total-cost currency"></span>
                            <button  type="button" id="" class="gs-button booking-next" disabled="disabled">Book</button>
                          </div>
                        </section>
                     </bf-services-summary>

  


                  </div>
               </div>
            </div>
         </section>
         <!-- end ngIf: state.isMode(MODES.SERVICES) -->
         <!-- STEP 2 -->
         <h3>step 2</h3>
         <section class="booking-flow-section booking-flow-appointment">
            <div class="grid-container-full">
               <div class="col-4-8 grid">
                  <div class="booking-flow-steps cell">
                     <bf-appointment-header>
                        <a href="/" class="logo-link">
                        <h2>VAPOR</h2>
                        </a>
                        <div class="step-details ng-binding">Bước 2 - 4</div>
                        <h1 class="booking-flow-title">Chi tiết lịch hẹn.</h1>
                        
                     </bf-appointment-header>
                  </div>
                  <div class="booking-flow-content cell">
                     <div class="gs-form ng-pristine ng-invalid ng-invalid-required form-location" novalidate="" autocomplete="off">
                        <label class="gs-label">Địa điểm của bạn ?</label>
                        <div class="gs-formatted-address">
                           <input force-selection="true" googleplace="" bind="address" type="text" name="fullAddress" placeholder="Nhập địa chỉ của bạn " id="booking-address" class="street gs-textbox ng-pristine ng-untouched ng-isolate-scope ng-invalid ng-invalid-required" required="" autocomplete="on" value="385 Trần Hưng Đạo, Ho Chi Minh City, Ho Chi Minh">
                           <i class="gs-icon fa fa-map-marker" aria-hidden="true"></i>
                           <input type="hidden" id="booking-latitude" name="lattitude" value="10.7602476"/>
                           <input type="hidden" id="booking-longitude" name="longitude" value="106.68894369999998"/>
                        </div>
                        
                        <bf-address-tags>
                           <div class="address-type-fields">
                              <label class="gs-label">Vị trí này là?</label>
                              <div class="gs-radio-buttons">
                                 <?php foreach ($this->locations as $location) {?>
                                 <div class="gs-radio ng-scope" ng-repeat="addressType in ADDRESS_TYPES">
                                    <input type="radio" id="addressTypes_<?=$location->getId()?>" name="type_location" class="ng-pristine ng-untouched ng-valid" value="<?=$location->getId()?>">
                                    <label for="addressTypes_<?=$location->getId()?>" class="ng-binding"><?=$location->getLocationTitle()?></label>
                                 </div>
                                 <?php }?>
                              </div>
                           </div>
                        </bf-address-tags>
                        <label class="gs-label">Thời gian?</label>
                        <div class="gs-formatted-address">
                          <input id="datetimepicker" type="text" class="street gs-textbox ng-pristine ng-untouched ng-isolate-scope ng-invalid ng-invalid-required">
                          <i class="gs-icon fa fa-calendar" aria-hidden="true"></i>
                        </div>
                        
                        <button type="button" class="address-button gs-button booking-next" style="">Tiếp tục </button>
                     </div>
                     <bf-order-summary>
                        <div class="order-summary">
                           <h2 class="order-title">Các dịch vụ đã đặt</h2>
                           <ul class="order-services">
                            <li class="edit">
                               <a href="javascript:void(0)">Chỉnh sửa </a>
                            </li>
                           </ul>
                        </div>
                     </bf-order-summary>
                  </div>
               </div>
            </div>
         </section>

         <!-- STEP 3 -->
         <h3>step 3</h3>
         <section class="booking-flow-section booking-flow-authentication" style="">
          <div class="grid-container-full">
            <div class="col-4-8 grid">
              <div class="booking-flow-steps cell">
                     <bf-appointment-header>
                        <a href="/" class="logo-link">
                        <h2>VAPOR</h2>
                        </a>
                        <div class="step-details ng-binding">Bước 3 - 4</div>
                        <h1 class="booking-flow-title">Đăng ký để tiếp tục đặt hàng.</h1>
                        
                     </bf-appointment-header>
                  </div>
              <div class="booking-flow-content cell">
                <h3>login</h3>
                <?php echo $this->action('login', 'authenticate', 'application', array('embed' => true, 'hidden' => false))?>
                <h3>register</h3>
                <?php echo $this->action('register', 'authenticate', 'application', array('embed' => true, 'hidden' => true))?>
              </div>
            </div>
          </div>
        </section>
      </div>
      <!-- ngIf: showDebugger && state -->
   </bf-booking-flow>
</div>