
<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="UTF-8">
  <link rel="profile" href="http://gmpg.org/xfn/11">

  <meta name="google-signin-client_id" content="<?= Zend_Registry::get('configs')->google->clientID?>">
  
  <!-- Styles -->
  <link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/animate.min.css")?>">
  <link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/bootstrap-dropdownhover.min.css")?>">
  <link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/glamsquad.css");?>">
  <link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/popup.css")?>">
  <link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/login-main.css?v=2");?>">
  <link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/home.css");?>">
  <link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/custom.css")?>">
  <link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/font-awesome.min.css")?>">
  
  <?php echo $this->partial('partials/seo.phtml')?>

  <script>
    <?php $user = $this->authen();?>
    var USER_ID = '<?=$user ? $user->getId() : ''?>';
  </script>
</head>
<body class="">
  <?= $this->partial('partials/social.phtml');?>
  <div class="site-container">
    <?php echo $this->partial('partials/topmenu.phtml')?>
    <main class="site-main">

    <?php echo $this->layout()->content?>

    </main>
  </div>
  

  <?= $this->partial("partials/js-booking.phtml")?>

</body></html>
