
<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta name="google-signin-client_id" content="<?= Zend_Registry::get('configs')->google->clientID?>">

  <link rel="profile" href="http://gmpg.org/xfn/11">

  <!-- Styles -->
  <link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/glamsquad.css");?>">
  <link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/home.css");?>">
  <link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/popup.css")?>">
  <link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/custom.css")?>">
  <link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/font-awesome.min.css")?>">
  <link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/flexslider.css")?>">

  <title>Vapor</title>
  
  <?php echo $this->partial('partials/seo.phtml')?>
</head>
<body class="">
  <?= $this->partial('partials/social.phtml');?>
  <div class="site-container">
    <?php echo $this->partial('partials/topmenu.phtml')?>

    <main class="site-main">
      <div class="page-container components">

      <section class="component-hero">
        <picture>
          <img src="<?php echo $this->baseUrl("static/images/home-slide-1.png");?>" alt="">
        </picture>
        <div class="hero-copy">
          <hgroup class="headline-group">
            <h1 class="headline"></h1>
            <h2 class="subheadline"></h2>
          </hgroup>
          <a href="/book/" class="gs-button inline" style="max-width: 400px;width: 400px;">Đặt ngay dịch vụ</a>
        </div>
      </section>

      <?php echo $this->partial('partials/section-services.phtml')?>

<section class="component-how-it-works">
  <div class="grid-container">
    <div class="grid">
      <div class="cell">
        <ul class="how-it-works">
            <li>
              <h3 class="headline">lựa chọn thời gian của bạn</h3>
              <figure class="icon">
                <img src="<?php echo $this->baseUrl("static/images/icon-clock.png");?>" class="lipstick" alt="">
              </figure>
              <p class="description">bạn luôn gặp vấn đề về máy lạnh, chúng tôi luôn sẵn sàng, hãy lựa chọn thời gian phù hợp với bạn.</p>
            </li>
            <li>
              <h3 class="headline">đặt dịch vụ</h3>
              <figure class="icon">
                <img src="<?php echo $this->baseUrl("static/images/icon-mobile.png");?>" class="calendar" alt="">
              </figure>
              <p class="description">lựa chọn nhu cầu của bạn trên web hoặc ứng dụng. Vapor sẽ xác nhận dịch vụ và lịch hẹn.</p>
            </li>
            <li>
              <h3 class="headline">đội ngũ chuyên nghiệp</h3>
              <figure class="icon">
                <img src="<?php echo $this->baseUrl("static/images/icon-worker.png");?>" class="team" alt="">
              </figure>
              <p class="description">chuyên viên kỹ thuật với đầy đủ dụng cụ sẽ xuất hiện đúng giờ trước cửa nhà bạn.</p>
            </li>
          </ul>
      </div>
    </div>
  </div>
</section>

<section class="component-news">
  <div class="grid-container">
    <div class="grid">
      <div class="cell">
        <h2 class="news-headline">Cảm nhận của khách hàng</h2>
        <ul class="news-items">
                        <li>
                <a href="/book/" class="news-link">
                  <picture>
                    <source media="(min-width: 768px)" srcset="https://www.glamsquad.com/wp-content/uploads/2017/06/Glamsquad_Desktop_WhatsNew_385x256@2x-385x256.jpg 1x,
                              https://www.glamsquad.com/wp-content/uploads/2017/06/Glamsquad_Desktop_WhatsNew_385x256@2x.jpg 2x">
                    <source srcset="https://www.glamsquad.com/wp-content/uploads/2017/09/Glamsquad_Mobile_WhatsNew_335x225@2x-335x225.jpg 1x,
                              https://www.glamsquad.com/wp-content/uploads/2017/09/Glamsquad_Mobile_WhatsNew_335x225@2x.jpg 2x">
                    <img src="https://www.glamsquad.com/wp-content/uploads/2017/06/Glamsquad_Desktop_WhatsNew_385x256@2x.jpg" alt="" class="news-image">
                  </picture>
                </a>
                <p class="news-subheadline"></p>
                <p class="news-description"></p>
              </li>
                        <li>
                <a href="/book/" class="news-link">
                  <picture>
                    <source media="(min-width: 768px)" srcset="https://www.glamsquad.com/wp-content/uploads/2017/06/Hallwoeen_770x512-385x256.jpg 1x,
                              https://www.glamsquad.com/wp-content/uploads/2017/06/Hallwoeen_770x512.jpg 2x">
                    <source srcset="https://www.glamsquad.com/wp-content/uploads/2017/06/Hallwoeen_670x450-335x225.jpg 1x,
                              https://www.glamsquad.com/wp-content/uploads/2017/06/Hallwoeen_670x450.jpg 2x">
                    <img src="https://www.glamsquad.com/wp-content/uploads/2017/06/Hallwoeen_770x512.jpg" alt="" class="news-image">
                  </picture>
                </a>
                <p class="news-subheadline"></p>
                <p class="news-description"></p>
              </li>
                        <li>
                <a href="https://www.coverfx.com/pages/glamsquad" class="news-link">
                  <picture>
                    <source media="(min-width: 768px)" srcset="https://www.glamsquad.com/wp-content/uploads/2017/06/CoverFX_770x512-1-385x256.jpg 1x,
                              https://www.glamsquad.com/wp-content/uploads/2017/06/CoverFX_770x512-1.jpg 2x">
                    <source srcset="https://www.glamsquad.com/wp-content/uploads/2017/06/CoverFX_670x450-335x225.jpg 1x,
                              https://www.glamsquad.com/wp-content/uploads/2017/06/CoverFX_670x450.jpg 2x">
                    <img src="https://www.glamsquad.com/wp-content/uploads/2017/06/CoverFX_770x512-1.jpg" alt="" class="news-image">
                  </picture>
                </a>
                <p class="news-subheadline"></p>
                <p class="news-description"></p>
              </li>
                  </ul>
      </div>
    </div>
  </div>
</section>

    </div>
  </main>
  
  <?php echo $this->partial('partials/footer.phtml')?>
</div>

  <?= $this->partial("partials/js.phtml")?>
</body></html>
