
  <link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/login.css?v=1");?>">
<?php if ($this->success) {?>
<section class="component-hero">
      <div class="hero-copy">
        <div class="grid-container">
          <div class="main-body-container">
            <div class="login-background">
              <div class="row">
<h2>Đơn tham gia của bạn đã được ghi nhận vào hệ thống.</h2>
</div></div></div></div></div></section>
<?php } else {?>

  <link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/jquery-ui.min.css")?>">
  <form accept-charset="UTF-8" action="/participation" class="gs-form simple_form analytics-event" id="form-participan" method="post">
    <h3>step 1</h3>
    <section class="component-hero participan">
      <div class="participan background"></div>
      <div class="hero-copy participan">
        <div class="grid-container">
          <div class="main-body-container">
            <div class="login-background">
              <div class="row">
                
                  <div style="margin:0;padding:0;display:inline">
                    <input name="<?= $this->form->getElements()['csrf']->getName()?>" type="hidden" value="<?= $this->form->getElements()['csrf']->getValue()?>">
                  </div>
                  <div class="login-block">
                    <h2 alt="Login to Vapor" class="larger center">Tham gia cùng vapor</h2>
                    <div class="error"><?= $this->error ? '<p class="error">'.$this->error.'</p>' : "" ?>  </div>
                    <div class="form-fields-wrapper">
                      <div class="pad-top">
                         <div class="form-line">
                            <div class="input email required user_session_email">
                              <input class="required" id="fullname" name="enroll_fullname" type="text" placeholder="Họ và Tên">
                            </div>
                         </div>
                      </div>
                    </div>
                    <div class="form-fields-wrapper">
                      <div class="pad-top">
                         <div class="form-line">
                            <div class="input email required user_session_email">
                              <input class="required" id="email" name="enroll_email" type="email" placeholder="Email">
                            </div>
                         </div>
                      </div>
                    </div>
                    <div class="form-fields-wrapper">
                        <div class="form-steps-bottom"></div>
                        <input id="participan-next" class="button btn-full push-top btn-primary" name="commit" type="button" value="BẮT ĐẦU">
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <h3>step 2</h3>
    <section>
      <div class="hero-copy">
        <div class="grid-container">
          <div class="main-body-container">
            <div class="login-background">
              <div class="row">
                  <div class="login-block participation-step2">
                    <h2 alt="Login to Vapor" class="larger center">Tham gia cùng vapor</h2>
                    <div class="error"><?= $this->error ? '<p class="error">'.$this->error.'</p>' : "" ?>  </div>
                    <h4>Thông tin cá nhân</h4>
                    <div class="form-fields-wrapper">
                      <div class="pad-top">
                        <div class="form-label">Số điện thoại</div>
                        <div class="form-line">
                          <div class="required">
                            <input class="required" id="phone" name="enroll_phone" type="text">
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="form-fields-wrapper">
                      <div class="pad-top">
                        <div class="form-label">Xác nhận số điện thoại</div>
                         <div class="form-line">
                            <div class="required">
                              <input class="required" id="" name="repeatphone" type="text">
                            </div>
                         </div>
                      </div>
                    </div>
                    <div class="form-fields-wrapper line">
                      <div class="pad-top">
                        <div class="form-label">Giới tính</div>
                        <div class="form-line">
                          <select class="required" name="enroll_gender">
                            <option value="male">Nam</option>
                            <option value="female">Nữ</option>
                            <option value="other">Khác</option>
                          </select>
                        </div>
                      </div>
                    </div>
                    <div class="form-fields-wrapper tuple">
                      <div class="pad-top">
                        <div class="form-label">Số CMND</div>
                         <div class="form-line">
                            <div class="required">
                              <input class="required" id="" name="enroll_identifier" type="text">
                            </div>
                         </div>
                      </div>
                    </div>
                    <div class="form-fields-wrapper tuple">
                      <div class="pad-top">
                        <div class="form-label">Nơi cấp</div>
                         <div class="form-line">
                            <div class="required">
                              <input class="required" id="" name="enroll_issueby" type="text">
                            </div>
                         </div>
                      </div>
                    </div>
                    <div class="form-fields-wrapper tuple">
                      <div class="pad-top">
                        <div class="form-label">Ngày cấp</div>
                         <div class="form-line">
                            <div class="required">
                              <input class="required" id="datepicker" name="enroll_issueon" type="text">
                            </div>
                         </div>
                      </div>
                    </div>
                    <div class="form-fields-wrapper line">
                      <div class="pad-top">
                        <div class="form-label">Địa chỉ thường trú </div>
                        <div class="form-line">
                            <div class="required">
                              <input class="required" id="" name="enroll_address" type="text">
                            </div>
                         </div>
                      </div>
                    </div>
                    <div class="form-fields-wrapper line">
                      <div class="pad-top">
                        <div class="form-label">Chỗ ở hiện nay</div>
                        <div class="form-line">
                            <div class="required">
                              <input class="required" id="" name="enroll_tempaddress" type="text">
                            </div>
                         </div>
                      </div>
                    </div>
                    <div class="form-fields-wrapper">
                      <div class="pad-top">
                        <div class="form-label">Tình trạng gia đình</div>
                        <div class="form-line">
                          <select class="required" name="enroll_marital">
                            <option value="single">Độc thân</option>
                            <option value="maried">Đã kết hôn</option>
                            <option value="other">Khác</option>
                          </select>
                        </div>
                      </div>
                    </div>
                    <div class="form-fields-wrapper">
                      <div class="pad-top">
                        <div class="form-label">Tình trạng sức khoẻ</div>
                         <div class="form-line">
                          <select class="required" name="enroll_healthy">
                            <option value="verygood">Rất Tốt</option>
                            <option value="good">Tốt</option>
                            <option value="other">Khác</option>
                          </select>
                        </div>
                      </div>
                    </div>

                    <div class="form-fields-wrapper line">
                      <div class="pad-top">
                        <h4>Kinh nghiệm làm việc</h4>
                      </div>
                    </div>
                    
                    <div class="form-fields-wrapper fullline">
                      <div class="pad-top">
                        <div class="form-label">Bạn có thể thực hiện tốt những công việc nào (đánh dấu vào tất cả các công việc mà bạn có thể thực hiện)</div>
                        <div class="form-line">
                          <?php foreach ($this->experiences as $row) {?>
                            <div class="option">
                              <div class="label"><?= $row->getPostTitle()?></div>
                              <input type="checkbox" name="experience[]" value="<?= $row->getId()?>"> 
                            </div>
                          <?php }?>
                          
                         </div>
                      </div>
                    </div>
                    
                    <div class="form-fields-wrapper line">
                      <div class="pad-top">
                        <div class="form-label" style="width: 50%;">Số năm kinh nghiệm làm việc</div>
                        <div class="form-line">
                          <select value="required" name="enroll_year">
                            <option>0 - 6 tháng</option>
                            <option>6 tháng - 1 năm</option>
                            <option>1 năm - 3 năm</option>
                            <option>3 năm - 5 năm</option>
                            <option>+5 năm</option>
                          </select>
                        </div>
                      </div>
                    </div>

                    <div class="form-fields-wrapper fullline">
                      <div class="pad-top">
                        <div class="form-label">Các kỹ năng khác</div>
                        <div class="form-line">
                            <div class="required">
                              <textarea name="enroll_skills"></textarea>
                            </div>
                         </div>
                      </div>
                    </div>

                    <div class="form-fields-wrapper fullline">
                      <div class="pad-top">
                        <div class="form-label">Bạn có những dụng cụ gì cho công việc - đánh dấu vào các dụng cụ mà bạn có thể chuẩn bị</div>
                        <div class="form-line">
                          <?php foreach ($this->tools as $row) {?>
                          <div class="option fullline">
                            <input type="checkbox" name="tools[]" value="<?= $row->getId()?>"> 
                            <div class="label"><?= $row->getToolTitle()?></div>
                          </div>
                          <?php }?>
                         </div>
                      </div>
                    </div>

                    <div class="form-fields-wrapper line">
                      <div class="pad-top">
                        <div class="form-label" style="width: 60%">Bạn biết đến VAPOR qua phương tiện nào</div>
                        <div class="form-line">
                          <select name="enroll_know">
                            <option>Quảng cáo</option>
                            <option>Khác</option>
                          </select>
                        </div>
                      </div>
                    </div>

                    <div class="form-fields-wrapper fullline">
                      <div class="pad-top">
                          <div class="option fullline">
                            <input type="checkbox" class="required" name="terms">
                            <div class="label terms"> Tôi đồng ý với <a data-toggle="modal" data-target="#using-term" href="#">Điều khoản Sử dụng</a> của Vapor và bằng cách nhấp vào đây, tôi đồng ý rằng Vapor hoặc các đại diện của Vapor có thể liên hệ với tôi qua email, điện thoại hoặc SMS (bao gồm cả hệ thống quay số bằng điện thoại tự động) theo địa chỉ email hoặc số điện thoại mà tôi cung cấp, ao gồm cả mục đích tiếp thị. Tôi đã đọc và hiểu <a data-toggle="modal" data-target="#privacy-term" href="#">Tuyên bố về Quyền Riêng Tư</a> có liên quan.</div>
                          </div>
                        </div>
                    </div>

                    <div class="form-fields-wrapper center">
                        <div class="form-steps-bottom"></div>
                        <input id="participan-next" class="button btn-full push-top btn-primary" name="" type="submit" value="Nộp Đơn">
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    
  </form>
  <!-- Modal -->
  <div class="modal fade" role="dialog" id="using-term" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="">Điều khoản sử dụng</h4>
        </div>
        <div class="modal-body">
          <?=isset($this->term[1]) ? $this->term[1]->getPostContent() : ''?>
        </div>
        <div class="modal-footer">
          
        </div>
      </div>
    </div>
  </div>
   <div class="modal fade" role="dialog" id="privacy-term" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="">Quyền riêng tư</h4>
        </div>
        <div class="modal-body">
          <?=isset($this->term[0]) ? $this->term[0]->getPostContent() : ''?>
        </div>
        <div class="modal-footer">
          
        </div>
      </div>
    </div>
  </div>
  <?php }?>