<section class="component-services" style="background-color: #fff;">
  <div class="grid-container">
    <div class="grid">
      <div class="cell">
        <?php if (isset($this->exception)): ?>
        <div style="font-size: 10px;text-align: left;">
        <h3>Exception information:</h3>
        <p>
            <b>Message:</b> <?php echo $this->exception->getMessage() ?>
        </p>

        <h3>Stack trace:</h3>
        <pre><?php echo $this->exception->getTraceAsString() ?>
        </pre>

        <h3>Request Parameters:</h3>
        <pre><?php echo $this->escape(var_dump($this->request->getParams(), true)) ?>
        </pre>
        </div>
        <?php endif ?>
        <div class="container">
            <div class="content">
                <i class="fa fa-search" style="font-size:120px;color:#FF5959;margin-bottom:30px;"></i>
                                    <div class="title">Page not found</div>
                                
                                    <a href="/">Homepage</a> | 
                    <a href="javascript:history.back()">Go Back</a>
                            </div>
        </div>
    


      </div>
    </div>
  </div>
</section>