<html>
<head>
  <meta charset="UTF-8">
  <title>ERROR</title>
</head>

<body style="background-color: #DAECF0">

  <img src="/static/images/404.jpg" alt="Page Not Found (404)." style="position: absolute; left: 50%; top: 50%; margin-left: -285px; margin-top: -190px;">
  <?php if (isset($this->exception)): ?>
  
  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo $this->escape(var_dump($this->request->getParams(), true)) ?>
  </pre>

  <?php endif ?>
</body>

</html>
