<section class="component-services" style="background-color: #fff;">
  <div class="grid-container">
    <div class="grid">
      <div class="cell">
        <?php if (isset($this->exception)): ?>
        <div style="font-size: 10px;text-align: left;">
        <h3>Exception information:</h3>
        <p>
            <b>Message:</b> <?php echo $this->exception->getMessage() ?>
        </p>

        <h3>Stack trace:</h3>
        <pre><?php echo $this->exception->getTraceAsString() ?>
        </pre>

        <h3>Request Parameters:</h3>
        <pre><?php echo $this->escape(var_dump($this->request->getParams(), true)) ?>
        </pre>
        </div>
        <?php endif ?>
        <img src="/static/images/404.gif" alt="Page Not Found (404).">
      </div>
    </div>
  </div>
</section>