<link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/user.css")?>">
  <div class="account-page-container ng-scope">
   <div class="row previous-and-upcoming-control" id="previous-and-upcoming-control">
      <ul class="small-12 medium-7 large-8 columns">
        <li>
          <a data-toggle="tab" href="#upcoming-bookings-section" class="btn booking-tab" type="button">Đang đặt hàng</a>
        </li>
        <li>
          <a data-toggle="tab" href="#previous-bookings-section" class="btn booking-tab" type="button">Lịch sử</a>
        </li>
      </ul>
      <div class="account-page-main-content-block">
      <div class="ng-scope">
         <div class="row upcoming-bookings-section" id="upcoming-bookings-section">
          <?php if (count($this->history['comming'])) {?>
            <div class="">
               <div class="small-12 columns">
                  <div class="account-info-slab">
                     <div class="booking-details-column">
                      Thời gian
                     </div>
                     <div class="booking-details-column">
                      Chi tiết 
                     </div>
                  </div>
               </div>
               <?php foreach ($this->history['comming'] as $row) {?>
               
               <div class="small-12 columns">
                  <div class="account-info-slab">
                     <div class="booking-details-column">
                      <?= $row->getGrouporderDatetime()?>
                     </div>
                     <div class="booking-details-column">
                      <ul class="prices">
                        <li><span class="title">Số tiền: </span><span class="detail"><?= $row->getGrouporderCost()?></span></li>
                        <li><span class="title">Giảm giá:</span><span class="detail"><?= $row->getGrouporderDiscount()?></span></li>
                      </ul>
                     </div>
                  </div>
               </div>
               <?php }?>
            </div>
            <?php } else {?>
            <div class="">
               <div class="small-12 columns">
                  <div class="account-info-slab">
                     <img alt="Account-empty" class="push-bot" src="<?php echo $this->baseUrl('/static/images/empty-history.png')?>">
                     <p>You don't have any comming bookings</p>
                     
                  </div>
               </div>
            </div>
            
            <?php }?>
         </div>
         <div class="row previous-bookings-section ng-hide" id="previous-bookings-section">
            <?php if (count($this->history['pass'])) {?>
            <div class="">
               <div class="small-12 columns">
                  <div class="account-info-slab">
                     <div class="booking-details-column">
                      Thời gian
                     </div>
                     <div class="booking-details-column">
                      Chi tiết 
                     </div>
                  </div>
               </div>
               <?php foreach ($this->history['pass'] as $row) {?>
               
               <div class="small-12 columns">
                  <div class="account-info-slab">
                     <div class="booking-details-column">
                      <?= $row->getGrouporderDatetime()?>
                     </div>
                     <div class="booking-details-column">
                      <ul class="prices">
                        <li><span class="title">Số tiền: </span><span class="detail"><?= $row->getGrouporderCost()?></span></li>
                        <li><span class="title">Giảm giá:</span><span class="detail"><?= $row->getGrouporderDiscount()?></span></li>
                      </ul>
                     </div>
                  </div>
               </div>
               <?php }?>
            </div>
            <?php } else {?>
            <div class="">
               <div class="small-12 columns">
                  <div class="account-info-slab">
                     <img alt="Account-empty" class="push-bot" src="<?php echo $this->baseUrl('/static/images/empty-history.png')?>">
                     <p>You don't have any pass bookings</p>
                     
                  </div>
               </div>
            </div>
            
            <?php }?>
            
         </div>
      </div>
      
   </div>
   </div>
   
   
</div>