<div class="account-page-container ng-scope">
   <div class="row previous-and-upcoming-control" id="previous-and-upcoming-control">
      <ul class="small-12 medium-7 large-8 columns">
        <li>
          <a data-toggle="tab" href="#upcoming-bookings-section" class="btn booking-tab pressed-tab" type="button">Đang đặt hàng</a>
        </li>
        <li>
          <a data-toggle="tab" href="#previous-bookings-section" class="btn booking-tab" type="button">Lịch sử</a>
        </li>
      </ul>
      <div class="account-page-main-content-block">
      <div class="ng-scope">
         <div class="row upcoming-bookings-section" id="upcoming-bookings-section">
            <div class="">
               <div class="small-12 columns">
                  <div class="account-info-slab">
                     <img alt="Account-empty" class="push-bot" src="https://cache.hbfiles.com/assets/account-page/account-empty-014a7862a4a5e13d5addd7661e75be14.png">
                     <p>You don't have any upcoming bookings</p>
                     
                  </div>
               </div>
            </div>
            
         </div>
         <div class="row previous-bookings-section ng-hide" id="previous-bookings-section">
            <div class="">
               <div class="small-12 columns">
                  <div class="account-info-slab">
                     <img alt="Account-empty" class="push-bot" src="https://cache.hbfiles.com/assets/account-page/account-empty-014a7862a4a5e13d5addd7661e75be14.png">
                     <p>You don't have any past bookings</p>
                     
                  </div>
               </div>
            </div>
            
         </div>
      </div>
      
   </div>
   </div>
   
   
</div>