<nav class="pagination-wrapper">
   <ul class="pagination">
    
<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <li class=""><a href="<?= $this->url(array('page' => $this->first), 'article')?>">First</a></li>
<?php else: ?>
  <li class="disabled"><a>First</a></li>
<?php endif; ?>
 
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <li class=""><a href="<?= $this->url(array('page' => $this->previous), 'article')?>">&lt; Previous</a></li>
<?php else: ?>
  <li class="disabled"><a>&lt; Previous</a></li>
<?php endif; ?>

<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li class=""><a href="<?= $this->url(array('page' => $page), 'article')?>"><?= $page?></a></li>
  <?php else: ?>
    <li class="disabled"><a><?=$page?></a></li>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <li class=""><a href="<?= $this->url(array('page' => $this->next), 'article')?>">Next &gt;</a></li>
<?php else: ?>
  <li class="disabled"><a>Next &gt;</a></li>
<?php endif; ?>
 

<!-- Last page link -->
<?php if (isset($this->next)): ?>
   <li class=""><a href="<?= $this->url(array('page' => $this->last), 'article')?>">Last</a></li>
<?php else: ?>
  <li class="disabled"><a>Last</a></li>
<?php endif; ?>
 
</ul>
</nav>