<div class="pad-top2">
   <div class="or-line">
      <span class="or-text">or</span>
   </div>
</div>
<div class="pad-top2"></div>
<div class="form-fields-wrapper">
   <div class="center">
      <p class="smaller" style="padding-bottom: 0.5em">Password too hard to type?</p>
   </div>
</div>
<div class="form-fields-wrapper">
   <a href="javascript:void(0)" class="no-decoration block" data-event-name="facebook log in attempt" id="btnFB">
      <div class="push-top center btn-default btn-facebook">
         <i class="fa fa-facebook-square"></i>
         Log in with Facebook
      </div>
   </a>
   <a href="javascript:void(0)" class="no-decoration block" data-event-name="google log in attempt" id="btnGG">
      <div class="push-top center btn-default btn-google">
         <i class="fa fa-google-plus-square"></i>
         Log in with Google
      </div>
   </a>
</div>