<div class="pad-top2">
   <div class="or-line">
      <span class="or-text">hoặc </span>
   </div>
</div>
<div class="pad-top2"></div>
<div class="form-fields-wrapper">
   <div class="center">
      <p class="smaller" style="padding-bottom: 0.5em">Đăng nhập bằng tài khoản mạng xã hội </p>
   </div>
</div>
<div class="form-fields-wrapper" style="text-align: center">
   <a href="javascript:void(0)" class="no-decoration block" data-event-name="facebook log in attempt" id="btnFB" style="00%">
      <div class="push-top center btn-default btn-facebook">
         <i class="fa fa-facebook-square"></i>
         Đăng nhập bằng Facebook
      </div>
   </a>
   <a href="javascript:void(0)" class="no-decoration block" data-event-name="google log in attempt" id="btnGG" style="">
      <div class="push-top center btn-default btn-google">
         <i class="fa fa-google-plus-square"></i>
         Đăng nhập bằng Google
      </div>
   </a>
</div>