<ul class="booking-services services services-fix" id="sua-chua-khan-cap">
  <?php foreach ($this->service as $service) {?>
  <li class="service ng-scope" data-title="<?=$service->getServicesTitle()?>" data-service="<?=$service->getServicesTitle()?>">
    <div class="booking-cell">
      <div class="column">
        <div class="header"><p><?=$service->getServicesTypeMachineTitle()?></p></div>
        <img alt="BLOWOUT" class="service-image" src="<?=$service->getServicesImage()?>">
      </div>
      <input type="hidden" data-service-title="<?=$service->getServicesTitle()?>" data-machine-title="<?=$service->getServicesTypeMachineTitle()?>" data-service-id="<?=$service->getId()?>" data-power="0" data-service-count="" type="text" class="form-control text-center service-detail" data-service-cost="0" id="" value="0">
    </div>
  </li>
  <?php }?>
         
</ul>