
<div class="container main-container">
   <div class="col-sm-12  blog-content">
      <div class="blog-wrapper">
         <img class="featured-img" src="<?php echo $this->baseUrl($this->data->getPostImage())?>" alt="">
         <article>
            <span class="published"><span><time class="timeago" datetime="<?=$this->timeAgo($this->data->getPostUpdateTime())?>"></time></span></span>
            <div id="servisheroSharingButtons" class="clickable src-app-components-SharingButton-SharingButton-module-sharings">
             <button data-url="<?php echo $this->baseUrl('/bai-viet/'.$this->data->getId().'/'.$this->data->getPostSlug())?>.html" data-name="servishero_facebook" class="clickable src-app-components-SharingButton-SharingButton-module-link facebook-sharing-button">
                <div class="src-app-components-SharingButton-SharingButton-module-sharingItem src-app-components-SharingButton-SharingButton-module-facebook">
                   <div class="src-app-components-SharingButton-SharingButton-module-item">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" classname="src-app-components-SharingButton-SharingButton-module-icon" viewBox="0 0 24 24">
                         <g>
                            <path stroke-width="2px" stroke-linejoin="round" stroke-miterlimit="10" d="M18.768 7.5h-4.268v-1.905c0-.896.594-1.105 1.012-1.105h2.988v-3.942l-4.329-.013c-3.927 0-4.671 2.938-4.671 4.82v2.145h-3v4h3v12h5v-12h3.851l.417-4z"></path>
                         </g>
                      </svg>
                   </div>
                </div>
             </button>
             <button data-url="https://twitter.com/intent/tweet/?text=<?=$this->data->getPostTitle()?>&amp;url=<?php echo $this->baseUrl('/bai-viet/'.$this->data->getId().'/'.$this->data->getPostSlug())?>.html" data-name="servishero_twitter" class="clickable src-app-components-SharingButton-SharingButton-module-link twitter-sharing-button">
                <div class="src-app-components-SharingButton-SharingButton-module-sharingItem src-app-components-SharingButton-SharingButton-module-twitter">
                   <div class="src-app-components-SharingButton-SharingButton-module-item">
                      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" classname="src-app-components-SharingButton-SharingButton-module-icon" viewBox="0 0 24 24">
                         <path stroke-width="2px" stroke-linejoin="round" stroke-miterlimit="10" d="M23.407 4.834c-.814.363-1.5.375-2.228.016.938-.562.981-.957 1.32-2.019-.878.521-1.851.9-2.886 1.104-.827-.882-2.009-1.435-3.315-1.435-2.51 0-4.544 2.036-4.544 4.544 0 .356.04.703.117 1.036-3.776-.189-7.125-1.998-9.366-4.748-.391.671-.615 1.452-.615 2.285 0 1.577.803 2.967 2.021 3.782-.745-.024-1.445-.228-2.057-.568l-.001.057c0 2.202 1.566 4.038 3.646 4.456-.666.181-1.368.209-2.053.079.579 1.804 2.257 3.118 4.245 3.155-1.944 1.524-4.355 2.159-6.728 1.881 2.012 1.289 4.399 2.041 6.966 2.041 8.358 0 12.928-6.924 12.928-12.929l-.012-.588c.886-.64 1.953-1.237 2.562-2.149z"></path>
                      </svg>
                   </div>
                </div>
             </button>
             
          </div>
            <h1><?=$this->data->getPostTitle()?></h1>
            <div>
               <?=$this->data->getPostContent()?>
            </div>
         </article>
      </div>
   </div>
</div>
